# Generated by Django 3.0.4 on 2020-04-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='message_html',
        ),
    ]
