# Generated by Django 3.0.4 on 2020-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_remove_grievance_message_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
