# Generated by Django 3.0.4 on 2020-05-02 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('grievance', '0004_auto_20200502_1847'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0006_auto_20200424_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
